//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcHotel.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Admin
    {
        [Display(Name = "身份证号")]
        public string Aid { get; set; }
        [Display(Name = "密码")]
        //[Required(ErrorMessage="请输入密码")]
        //[StringLength(20)]
        public string Apwd { get; set; }
        [Display(Name = "姓名")]
        public string Aname { get; set; }
        [Display(Name = "电话号码")]
        public string Atel { get; set; }
        [Display(Name = "头像")]
        public string Apic { get; set; }
    }
}
