//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcHotel.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Book
    {
        [Display(Name = "入住时间")]
        public DateTime CheckinTime { get; set; }

        [Required(ErrorMessage = "号码不能为空")]
        [Display(Name = "电话号码")]
        [Remote("CheckCtel", "AdminBooks", ErrorMessage = "不存在此用户")]
        public string Ctel { get; set; }

        [Display(Name = "退房时间")]
        public DateTime CheckoutTime { get; set; }
        [Key]
        [Display(Name = "订单编号")]
        public int Bid { get; set; }
        [Display(Name = "房间类型")]
        public int RtypeID { get; set; }

        public virtual Customer Customer { get; set; }

        public virtual RoomInfo RoomInfo { get; set; }
        //public System.DateTime CheckinTime { get; set; }
        
        //public string Ctel { get; set; }
        //public System.DateTime CheckoutTime { get; set; }
        //public int Bid { get; set; }
        //public int RtypeID { get; set; }
    
        //public virtual Customer Customer { get; set; }
        //public virtual RoomInfo RoomInfo { get; set; }
    }
}
