//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcHotel.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class CheckIn
    {
        [Required(ErrorMessage = "不能为空")]
        [StringLength(18)]
        [Display(Name="身份证号")]
        //[RegularExpression(@"\d{17}[\d|x]|\d{15}", ErrorMessage = "身份证号码格式错误")]
        public string Gid { get; set; }

        [Required(ErrorMessage = "不能为空")]
        [StringLength(3, ErrorMessage = "房间号为三位数字")]
        [Display(Name = "房间号")]
        public string Rno { get; set; }
        [Required(ErrorMessage = "不能为空")]
        [Display(Name = "入住时间")]
        public DateTime CheckinTime { get; set; }
        [Required(ErrorMessage = "不能为空")]
        [Display(Name = "退房时间")]
        public DateTime CheckoutTime { get; set; }

        [Column(TypeName = "money")]
        [Display(Name = "押金")]
        public decimal Cash { get; set; }

        [Key]
        public int CheID { get; set; }

        public virtual Guest Guest { get; set; }

        public virtual RoomNum RoomNum { get; set; }
        //public string Gid { get; set; }
        //public string Rno { get; set; }
        //public System.DateTime CheckinTime { get; set; }
        //public System.DateTime CheckoutTime { get; set; }
        //public decimal Cash { get; set; }
        //public int CheID { get; set; }

        //public virtual Guest Guest { get; set; }
        //public virtual RoomNum RoomNum { get; set; }
    }
}
