//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcHotel.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class Guest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]

        public Guest()
        {
            CheckIn = new HashSet<CheckIn>();
        }

        [Required]
        [StringLength(10)]
        [Display(Name = "姓名")]
        public string Gname { get; set; }
        [Display(Name = "性别")]
        public bool Gsex { get; set; }

        [Key]
        [StringLength(18)]
        [Display(Name = "身份证号")]
        public string Gid { get; set; }

        [Required]
        [StringLength(15)]
        [Display(Name = "电话号码")]
        public string Gtel { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckIn> CheckIn { get; set; }
        //public Guest()
        //{
        //    this.CheckIn = new HashSet<CheckIn>();
        //}

        //public string Gname { get; set; }
        //public bool Gsex { get; set; }
        //public string Gid { get; set; }
        //public string Gtel { get; set; }

        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<CheckIn> CheckIn { get; set; }
    }
}
