//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcHotel.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JustHotelPluscEntities : DbContext
    {
        public JustHotelPluscEntities()
            : base("name=JustHotelPluscEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Book> Book { get; set; }
        public virtual DbSet<CheckIn> CheckIn { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Guest> Guest { get; set; }
        public virtual DbSet<RoomInfo> RoomInfo { get; set; }
        public virtual DbSet<RoomNum> RoomNum { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<BookView> BookView { get; set; }
        public virtual DbSet<CheckInView> CheckInView { get; set; }
        public virtual DbSet<CustmerInfo> CustmerInfo { get; set; }
        public virtual DbSet<GuestInfo> GuestInfo { get; set; }
        public virtual DbSet<RoomInfoView> RoomInfoView { get; set; }
        public virtual DbSet<RoomTypeInfo> RoomTypeInfo { get; set; }
    }
}
