//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomInfoView
    {
        public string Rno { get; set; }
        public string Rtype { get; set; }
        public Nullable<int> Rfloor { get; set; }
        public Nullable<int> Rlive { get; set; }
        public Nullable<bool> Rwindow { get; set; }
        public Nullable<decimal> Rcost { get; set; }
        public Nullable<bool> Rreservation { get; set; }
    }
}
