//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcHotel.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class RoomInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoomInfo()
        {
            this.Book = new HashSet<Book>();
            this.RoomNum = new HashSet<RoomNum>();
        }

        [Required]
        [StringLength(20)]
        [Display(Name = "房间类型")]
        public string Rtype { get; set; }
        [Display(Name = "楼层")]
        public int? Rfloor { get; set; }
        [Display(Name = "可容纳人数")]
        public int? Rlive { get; set; }
        [Display(Name = "是否有窗")]
        public bool? Rwindow { get; set; }

        [Column(TypeName = "money")]
        [Display(Name = "价格")]
        public decimal? Rcost { get; set; }
        [Display(Name = "是否可退")]
        public bool? Rreservation { get; set; }
        [Display(Name = "图片")]
        public string Rpic { get; set; }

        [Key]
        [Display(Name = "房间类型")]
        public int RtypeID { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Book> Book { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomNum> RoomNum { get; set; }
    }
}
